---
title: "Projeto UCFootprint"
output: flexdashboard::flex_dashboard
runtime: shiny
---

Evolução do impacto antrópico nas Unidades de Conservação na Mata Atlântica
=====================================
```{r setup, warning=FALSE, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(leaflegend)
library(leaflet)
#library(leaflet.extras)
library(shiny)
library(shinyjs)
library(highcharter)
library(DT)
library(plotly)

Dashboard_Data<-read.csv("DashboardData.csv")
```

```{r}
addMapResetButton <- function(leaf) {
  leaf %>%
    addEasyButton(
      easyButton(
        icon = "ion-arrow-shrink", 
        title = "Reset View", 
        onClick = JS(
          "function(btn, map){ map.setView(map._initialCenter, map._initialZoom); }"
        )
      )
    ) %>% 
    htmlwidgets::onRender(
      JS(
"
function(el, x){ 
  var map = this; 
  map.whenReady(function(){
    map._initialCenter = map.getCenter(); 
    map._initialZoom = map.getZoom();
  });
}"
      )
    )
}
```

```{r message=FALSE, warning=FALSE, include=FALSE}
Dashboard_Data<-Dashboard_Data%>%
              mutate(ids=UC_NAME2)%>%
  as_tibble()

MEDIA_UC_MA<-Dashboard_Data%>%
  summarise_at(vars(HFP1993: HFP2013), mean, na.rm = TRUE)%>%
  mutate(UC_NAME2="MEDIA_UC_MA")%>%
  mutate(ids="MEDIA_UC_MA")

#Add MEDIA as a new observation
Dashboard_Data<-Dashboard_Data%>%add_case(MEDIA_UC_MA)

#Check if MEDIA is here
#Dashboard_Data%>%tail(1)

Dashboard_Data_MEDIA<-Dashboard_Data%>%
filter(UC_NAME2=="MEDIA_UC_MA")%>% select(UC_NAME2,PLA_MAN2,MATA_ARE2,HFP1993:HFP2013)%>%
  pivot_longer(!c(UC_NAME2:MATA_ARE2),names_to="ANO",values_to="Impacto")%>%
  mutate(ANO=str_replace(ANO,"HFP", ""))%>%
  mutate(Impacto=round(Impacto,2))



pal_man<- colorFactor(c("tomato","royalblue2"), domain = df<-Dashboard_Data$PLA_MAN2)
df<-Dashboard_Data
```


Column {.tabset}
-----------------------------------------------------------------------

### Mapa interativo

```{r}
output$map <- renderLeaflet({

leaflet(Dashboard_Data, width="1000px")%>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
    addMiniMap()%>%
 #    addMarkers(lng = ~Long, lat = ~Lat)%>%
  addMapResetButton()%>%
addCircleMarkers(
           layerId = ~UC_NAME2, 
                 lng = ~Long, lat = ~Lat,
#                 clusterOptions = markerClusterOptions(),
                  color = ~ifelse(PLA_MAN2=="Sim","Blue","Red"),
#                       color = ~pal_man(PLA_MAN2),
             popup = ~paste0(UC_NAME2,
	"<br/><strong>Jurisprudence</strong>:",ESF_ADM2,
	"<br/><strong>Management plan.:</strong>",PLA_MAN2))
})

leafletOutput('map')  
```



### O projeto


Passar aqui para frente, adicionar a metodologia, figuras e exemplos...
Foto explicativa com o layout tbm



Column {data-width=350, height=450}
-----------------------------------------------------------------------

### Evolução do impacto antrópico - 1993 a 2013


```{r}

#click_marker <- eventReactive(input$map_marker_click, {
click_marker <- eventReactive(input$map_marker_click, {
     x<-input$map_marker_click
       if(is.null(input$map_marker_click)){
       return(input$reset) 
    }else{
        return(x$id)
      }
})



#Funciona
data_for_chart <- reactive({
  return(df[df$UC_NAME2 == click_marker(), ])
})


renderPlotly({
    data_for_chart2<-data_for_chart()%>%
  as_tibble()%>%
  select(UC_NAME2,PLA_MAN2,MATA_ARE2,HFP1993:HFP2013)%>%
  pivot_longer(!c(UC_NAME2:MATA_ARE2),names_to="ANO",values_to="Impacto")%>%
  mutate(ANO=str_replace(ANO,"HFP", ""))%>%
    mutate(Impacto=round(Impacto,2))
  Dashboard_Data_MEDIA%>%
  plotly::plot_ly(.,
        x = .$ANO,
          y = .$Impacto,
          type = "scatter",
          mode = 'lines+markers',name="Mata Atlântica")%>%
    add_trace(data_for_chart2, 
	x = data_for_chart2$ANO, 
		y = data_for_chart2$Impacto, mode = "lines+markers",name=data_for_chart2$UC_NAME2) %>%
  layout(hovermode = "x unified",
    #title ="Evolução do impacto antrópico",
         yaxis = list(title = "Impacto Antrópico",range = c(0,55)),
    showlegend = T, 
    legend = list(orientation = 'h')
  )

})

```


### Chart C

AAAA




Sobre {data-orientation=rows}
=====================================



Row {data-height=600}
-----------------------------------------------------------------------

### Sobre
Seja bem-vindo(a) ao projeto "Evolução do impacto antrópico nas Unidades de Conservação da Mata Atlântica. 

Aqui os bancos de dados que serão unidos serão o Global Human Footprint, que mede o impacto antrópico a nível global e com precisão de 1km em diferentes períodos (1993-2013) que serão integrados com o banco de dados de unidades de conservação desenvolvido em Loss et al. (In press). Atualmente o projeto encontra-se em fase de desenvolvimento então o que vc está vendo é apenas um protótipo para demonstração interna. O projeto está sendo desenvolvido pelo pesquisador Dr. Gabriel Santos em parceria com o Instituto Nacional da Mata Atlântica (INMA).

A ideia do projeto é unir diferentes bancos em um aplicativo de fácil visualização para tomada de decisão e insights sobre o papel das Unidades de Conservação no Brasil.




Row {data-height=600}
-----------------------------------------------------------------------

### Metodologia


AAAAAAAAAAA



Row {data-height=600}
-----------------------------------------------------------------------
### Desenvolvedor e parceiros