---
title: "Evolução do impacto humano nas Unidades de conservação da Mata atlântica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

https://stackoverflow.com/questions/28938642/marker-mouse-click-event-in-r-leaflet-for-shiny
https://stackoverflow.com/questions/48474440/select-only-one-state-in-a-map-in-a-shiny-application
https://stackoverflow.com/questions/37820782/flexdashboards-and-leaflet-and-marker-click-with-highcharts
https://www.thetidytrekker.com/post/dull-dashboards


```{r setup, warning=FALSE, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(leaflegend)
library(leaflet)
library(shiny)
library(highcharter)
library(DT)
library(plotly)
setwd("C:/Artigos e resumos publicados submetidos ideias/Em desenvolvimento/INMA/Footprint evolution  - Dashboard/Footprint")

dir()
Dashboard_Data<-read.csv("DashboardData.csv")
```


```{r message=FALSE, warning=FALSE, include=FALSE}
Dashboard_Data<-Dashboard_Data%>%
              mutate(ids=UC_NAME2)

pal_man<- colorFactor(c("tomato","royalblue2"), domain = df<-Dashboard_Data$PLA_MAN2)
df<-Dashboard_Data
```



Column {.tabset}
-----------------------------------------------------------------------

### Interactive leaflet

```{r}
output$map <- renderLeaflet({

leaflet(Dashboard_Data, height=500, width=1000)%>%
   addMiniMap()%>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
addMarkers(layerId = ~UC_NAME2, 
                 lng = ~Long, lat = ~Lat,
#                 clusterOptions = markerClusterOptions(),
#                  color = ~ifelse(PLA_MAN2=="Sim","Blue","Red"),
#                       color = ~pal_man(PLA_MAN2),
#                       color = ~Rich_pal(bins),
#                       color = ~pal(na.omit(Richness+1)),
             popup = ~paste0(UC_NAME2,
	"<br/><strong>Jurisprudence</strong>:",ESF_ADM2,
	"<br/><strong>Management plan.:</strong>",PLA_MAN2))
})

leafletOutput('map')  
```




Column {data-width=350}
-----------------------------------------------------------------------

### Chart B


```{r}
click_marker <- eventReactive(input$map_marker_click, {

  x <- input$map_marker_click

  return(x$id)

})


#Funciona
data_for_chart <- reactive({

 return(df[df$UC_NAME2 == click_marker(), ])

})

renderPlotly({
  
  data_for_chart()%>%
  as_tibble()%>%
  select(UC_NAME2,PLA_MAN2,MATA_ARE2,HFP1993:HFP2013)%>%
  pivot_longer(!c(UC_NAME2:MATA_ARE2),names_to="ANO",values_to="Impacto")%>%
  mutate(ANO=str_replace(ANO,"HFP", ""))%>%
  plotly::plot_ly(.,
        x = .$ANO,
          y = .$Impacto,
          type = "scatter",
          mode = 'lines+markers') 

})

```


### Chart C


